"""empty message

Revision ID: 24fa477ceaae
Revises: aac860bc80b8
Create Date: 2016-07-31 21:12:36.353242

"""

# revision identifiers, used by Alembic.
revision = '24fa477ceaae'
down_revision = 'aac860bc80b8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
