"""empty message

Revision ID: 29b52932d46d
Revises: 674d1cbf8da8
Create Date: 2016-08-01 23:15:40.654906

"""

# revision identifiers, used by Alembic.
revision = '29b52932d46d'
down_revision = '674d1cbf8da8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
