"""empty message

Revision ID: aac860bc80b8
Revises: None
Create Date: 2016-07-31 19:18:38.687970

"""

# revision identifiers, used by Alembic.
revision = 'aac860bc80b8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
